In [3]:

import brightway2 as bw
from  brightway2 import *
import ast
import pandas as pd
from lca_ef_if import lca_ef,lca_if

bw.projects.set_current("AEMEL Schropp MS v1 (Eleonora)")

In [17]:
excel_path = r"C:\Users\mael.mouhoub\Documents\2-Recherche\5-Git_repositories\ab-plugin-IF_analysis\ab_plugin_IF_analysis\utils\method_input.xlsx"        
if_panda = pd.read_excel(excel_path)
list_methods_if = list(if_panda["method"].unique())       
method_if_name = "Criticality method"
method_if = if_panda[if_panda["method"] == method_if_name]
key = ('AEMEL_schropp', 'b41bfd4f33a94e09aa95ac43db2716bf')

In [5]:
method_if

,product,activity,location,unit,category,key,cf,method
0,"End plates, Stainless steel","End plates, Stainless steel",GLO,kilogram,NaN,"('Base_component', '8559cd1e850245d2b39701b1d9...",10,Criticality method
1,"Bipolar plate, Stainless steel hot rolled","Bipolar plate, Stainless steel hot rolled",GLO,kilogram,NaN,"('Base_component', '78af86b0c6fb4c8ca20dc0dae7...",50,Criticality method
2,"Catalyst, Nickel Molybdenum","Catalyst, Nickel Molybdenum",GLO,kilogram,NaN,"('Base_component', '6fe174c6d6194959bd8633b273...",20,Criticality method

In [6]:
def lca_if(key,method_flows):
    #recupere la methode IF
    #fais un calcul de supply chain
    #identifie les activites necessaires
    #retourne un tableau
    random_method = list(methods)[1]
    method = Method(random_method)#random method we only need supply chain
    lca = LCA({key: 1}, random_method)
    lca.lci()
    lca.lcia()
    lca_score = lca.score
    activity_dict = lca.activity_dict
    supply_array = lca.supply_array
    print(lca_score)
    results_df = pd.DataFrame(columns=["Type",'Flow',"Inventory","CF", 'Activity', 'LCA Score'])
    for index,if_flows in method_flows.iterrows():
        key_flow = ast.literal_eval(if_flows["key"])
        results_df.loc[len(results_df)] = {
        "Type" : "IF",
        'Flow': if_flows["product"],
        'Activity': Database(key_flow[0]).get(key_flow[1])["name"],
        "Inventory":supply_array[activity_dict[key_flow]],
        "CF":if_flows["cf"],
        'LCA Score': if_flows["cf"] * supply_array[activity_dict[key_flow]],
        }
        print(key_flow)
        
    # Extraire les noms des colonnes et les données
    return(results_df)

In [18]:
random_method = list(methods)[1]
method = Method(random_method)#random method we only need supply chain
lca = LCA({key: 1}, random_method)
lca.lci()
lca.lcia()
lca_score = lca.score
activity_dict = lca.activity_dict
supply_array = lca.supply_array
print(lca_score)
results_df = pd.DataFrame(columns=["Type",'Flow',"Inventory","CF", 'Activity', 'LCA Score'])
for index,if_flows in method_if.iterrows():
    key_flow = ast.literal_eval(if_flows["key"])
    results_df.loc[len(results_df)] = {
    "Type" : "IF",
    'Flow': if_flows["product"],
    'Activity': Database(key_flow[0]).get(key_flow[1])["name"],
    "Inventory":supply_array[activity_dict[key_flow]],
    "CF":if_flows["cf"],
    'LCA Score': if_flows["cf"] * supply_array[activity_dict[key_flow]],
    }
    print(key_flow)
    
# Extraire les noms des colonnes et les données

18:34:02 | INFO | Created LCA object

0.0

KeyError: ('Base_component', '8559cd1e850245d2b39701b1d980e2a8_copy2')

In [22]:
key_flow in activity_dict

False

In [4]:
lca_if(key,method_if)

0.0
('Base_component', '8559cd1e850245d2b39701b1d980e2a8_copy2')
('Base_component', '78af86b0c6fb4c8ca20dc0dae7f51139_copy1')
('Base_component', '6fe174c6d6194959bd8633b273e192cc_copy1')

,Type,Flow,Inventory,CF,Activity,LCA Score
0,IF,"End plates, Stainless steel",1.0,10,"End plates, Stainless steel",10.0
1,IF,"Bipolar plate, Stainless steel hot rolled",0.0,50,"Bipolar plate, Stainless steel hot rolled",0.0
2,IF,"Catalyst, Nickel Molybdenum",0.0,20,"Catalyst, Nickel Molybdenum",0.0

In [6]:
key_flow

NameError: name 'key_flow' is not defined

In [ ]:
# -*- coding: utf-8 -*-
import re
import sys

from activity_browser import run_activity_browser

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run_activity_browser())

10:37:10 | INFO | Activity Browser version: 2.11.2
10:37:10 | INFO | Activity Browser version: 2.11.2
10:37:14 | INFO | Brightway2 data directory: C:\Users\mael.mouhoub\AppData\Local\pylca\Brightway3
10:37:14 | INFO | Brightway2 data directory: C:\Users\mael.mouhoub\AppData\Local\pylca\Brightway3
10:37:14 | INFO | Brightway2 current project: default
10:37:14 | INFO | Brightway2 current project: default
10:37:14 | INFO | Project settings directory: C:\Users\mael.mouhoub\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
10:37:14 | INFO | Project settings directory: C:\Users\mael.mouhoub\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
10:37:14 | INFO | Loaded tab 'ab_plugin_contribution_analysis'
10:37:14 | INFO | Loaded tab 'ab_plugin_contribution_analysis'
10:37:23 | INFO | Brightway2 current project: AEMEL Schropp MS v1 (Eleonora)
10:37:23 | INFO | Brightway2 current project: AEMEL Schropp MS v1 (Eleonora)
10:37:23 | INFO | Project settings directory: C:\Users\mael.mouhoub\AppData\Local\pylca\Brightway3\AEMEL-Schropp-MS-v1-Eleonora.77a1a4c3794bb8320e7e949391242c89
10:37:23 | INFO | Project settings directory: C:\Users\mael.mouhoub\AppData\Local\pylca\Brightway3\AEMEL-Schropp-MS-v1-Eleonora.77a1a4c3794bb8320e7e949391242c89
10:37:23 | INFO | Loaded tab 'ab_plugin_contribution_analysis'
10:37:23 | INFO | Loaded tab 'ab_plugin_contribution_analysis'
10:37:32 | INFO | Loaded tab 'ab_plugin_IF_analysis'
10:37:32 | INFO | Loaded tab 'ab_plugin_IF_analysis'

Selected Activity: AEM stack, plant with 1000 kg H2/d
, AEM stack, plant with 1000 kg H2/d
, GLO (key: ('AEMEL_schropp', 'b41bfd4f33a94e09aa95ac43db2716bf'))
Sélection: Database : AEMEL_schropp, Activity : b41bfd4f33a94e09aa95ac43db2716bf , Method_ef : ('EF v3.0', 'energy resources: non-renewable', 'abiotic depletion potential (ADP): fossil fuels'), Method_if : Criticality method

10:38:14 | INFO | Created LCA object
10:38:14 | INFO | Created LCA object
10:38:21 | INFO | Created LCA object
10:38:21 | INFO | Created LCA object
10:42:54 | ERROR | AttributeError: 'list' object has no attribute 'iterrows'
Traceback (most recent call last):
  File "C:\Users\mael.mouhoub\Documents\2-Recherche\5-Git_repositories\ab-plugin-IF_analysis\ab_plugin_IF_analysis\widgets\IFC_widget.py", line 160, in calcultate_if_ef
    result_if = lca_if(activity_key,method_if)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mael.mouhoub\Documents\2-Recherche\5-Git_repositories\ab-plugin-IF_analysis\ab_plugin_IF_analysis\utils\lca_ef_if.py", line 21, in lca_if
    for index,if_flows in method_flows.iterrows():
                          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'iterrows'
10:42:54 | ERROR | AttributeError: 'list' object has no attribute 'iterrows'
Traceback (most recent call last):
  File "C:\Users\mael.mouhoub\Documents\2-Recherche\5-Git_repositories\ab-plugin-IF_analysis\ab_plugin_IF_analysis\widgets\IFC_widget.py", line 160, in calcultate_if_ef
    result_if = lca_if(activity_key,method_if)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mael.mouhoub\Documents\2-Recherche\5-Git_repositories\ab-plugin-IF_analysis\ab_plugin_IF_analysis\utils\lca_ef_if.py", line 21, in lca_if
    for index,if_flows in method_flows.iterrows():
                          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'iterrows'

SystemExit: 0

c:\Users\mael.mouhoub\AppData\Local\anaconda3\envs\ab\Lib\site-packages\IPython\core\interactiveshell.py:3756: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [1]:
1+1

2